name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore ./CollectionLinqCI-master/CollectionLinqAssignment.sln

    - name: Build
      run: dotnet build ./CollectionLinqCI-master/CollectionLinqAssignment.sln --no-restore

    - name: Test
      run: dotnet test ./CollectionLinqCI-master/CollectionLinqAssignment.sln --no-build --verbosity normal
